<!DOCTYPE html>
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>

        <?php
        foreach ($rs as $cat) {
            echo "<p>" . $cat['name'] . ' - previsto: ' . $cat['limit'] . " | gasto: " . $cat['total'] . "</p>";
        }
        ?>

    </body>
</html>